name              "chef-client_test"
maintainer        "Opscode, Inc."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "This cookbook is used with test-kitchen to test the parent, chef-client cookbook"
version           "1.0.0"
